export const ADD_USER = "ADD_USER";
export const ADD_TRIPS = "ADD_TRIPS";
export const ADD_TRIP_DESTINATION = "ADD_TRIP_DESTINATION";
export const OTP_VERIFY_SUCCESS = "OTP_VERIFY_SUCCESS";
export const ADD_JOBS = "ADD_JOBS";
export const ADD_IMAGES = "ADD_IMAGES";
export const SET_IMAGES = "SET_IMAGES";
export const ADD_AUTH_TOKEN = "ADD_AUTH_TOKEN";
export const ADD_RECOMMENDED_SNAKS = "ADD_RECOMMENDED_SNAKS";
export const ADD_ALL_RECOMMENDED_SNAKS = "ADD_ALL_RECOMMENDED_SNAKS";
export const ADD_SNAKS = "ADD_SNAKS";
export const ADD_ADVENTURE_PREF = "ADD_ADVENTURE_PREF";
export const ADD_TIME_PREF = "ADD_TIME_PREF";
export const ADD_BLOCKED_LIST = "ADD_BLOCKED_LIST";
export const ADD_SNAK_PROFILE = "ADD_SNAK_PROFILE";
export const ADD_USER_SETTINGS = "ADD_USER_SETTINGS";
export const FILTER_RECOMMENDED = "FILTER_RECOMMENDED";

// Subscription
export const ADD_STRIPE_PUB_KEY = "GET_STRIPE_PUB_KEY";
export const ADD_STRIPE_PAYMENT_LIST = "GET_STRIPE_PAYMENT_LIST";
export const ADD_STRIPE_CARD_LIST = "GET_STRIPE_CARD_LIST";
// export const POST_STRIPE_CARD_ATTACH = "POST_STRIPE_CARD_ATTACH";
// export const PATCH_STRIPE_CARD = "PATCH_STRIPE_CARD";
// export const DELETE_STRIPE_CARD = "DELETE_STRIPE_CARD";

// Notifications
export const ADD_NOTIFICATION_PREFERENCES = "ADD_NOTIFICATION_PREFERENCES";
export const ADD_NOTIFICATIONS = "ADD_NOTIFICATIONS";

export const UPDATE_COUNT_NOTIFICATION = "UPDATE_COUNT_NOTIFICATION";

// Chats
export const ADD_CHATS = "ADD_CHATS";

// Online Status
export const HANDLE_ONLINE_STATUS = "HANDLE_ONLINE_STATUS";
export const UPDATE_ACTIVE_COUNT = "UPDATE_ACTIVE_COUNT";
